PC_MODE = False
FLASK_ENABLED = False

SENSOR_CONFIGURED = "TILT_B_INCL"  # "TILT_A_INCL"

URL_ONTOLOGY_DEPLOYMENT_LOCAL = "http://localhost:5000"
URL_ONTOLOGY_DEPLOYMENT_CLOUD = "http://192.168.27.28:8000/api"  # "http://35.195.86.253"

ONTOLOGY_SENSOR_NAME = "InclinationSensor"
ONTOLOGY_OBSERVABLE_PROPERTY = "Tilt"
