version: '3.9'

services:
  grafana:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    restart: unless-stopped
    env_file:
      - ENV/grafana.env
    volumes:
      - ./ENV/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - private

  postgres:
    image: postgres:15.0-alpine
    restart: unless-stopped
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - /var/opt/phd_postgres_backend/pg_data:/var/lib/postgresql/data/pgdata
    networks:
      - private

networks:
  private:
    driver: bridge
